cafe_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainpage.urls')),
    path('news/', include('news.urls')),
    path('menu/', include('menu.urls')),
    path('reserve/', include('reserve.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail', views.detail, name='detail'),
]

reserve/urls.py
from django.urls import path
from . import views

app_name = 'reserve'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:reserve_id>', views.detail, name='detail'),
    path('new_reserve', views.reserve_new, name='new_reserve'),
    path('<int:reserve_id>/edit', views.edit, name='edit'),
    path('<int:reserve_id>/delete', views.delete, name='delete'),
]

reserve/models.py
from django.db import models


class Res(models.Model):
    name = models.CharField(blank=False, max_length=20)
    datetime = models.DateTimeField(blank=False)
    num = models.IntegerField(blank=False)
    course = models.CharField(max_length=150)
    comment = models.CharField(blank=True, max_length=1000)

    def __str__(self):
        return self.name

reserve/forms.py
from django import forms


EMPTY_CHOICES = (
    ('', '-'*10),
)

NUM_CHOICES = (
    ('2', '2名'),
    ('3', '3名'),
    ('4', '4名'),
)

COURSE_CHOICES = (
    ('courseA', 'Aコース'),
    ('courseB', 'Bコース'),
    ('tables', '席のみ'),
)


class ResForm(forms.Form):
    name = forms.CharField(
        label='名前',
        max_length=20,
        required=True,
        widget=forms.TextInput()
    )

    datetime = forms.DateTimeField(
        label='日時',
        required=True,
        widget=forms.DateTimeInput(attrs={"type": "datetime-local"}),
        input_formats=['%Y-%m-%dT%H:%M']
    )

    num = forms.ChoiceField(
        label='人数',
        widget=forms.Select,
        choices=EMPTY_CHOICES + NUM_CHOICES,
        required=True,
    )

    course = forms.ChoiceField(
        label='コース',
        widget=forms.RadioSelect,
        choices=COURSE_CHOICES,
        required=True,
    )

    comment = forms.CharField(
        label='備考',
        max_length=1000,
        required=False,
        widget=forms.TextInput()
    )

reserve/views.py
from django.shortcuts import render, redirect
from .models import Res
from django.shortcuts import get_object_or_404
from .forms import ResForm


# 予約一覧
def index(request):
    reserves = Res.objects.all().order_by('datetime')
    return render(request, 'reserve/index.html', {'reserves': reserves})


# 予約詳細
def detail(request, reserve_id):
    reserve = get_object_or_404(Res, id=reserve_id)
    if request.method == 'POST':
        reserve.delete()
        return redirect('reserve:index')
    return render(request, 'reserve/detail.html', {'reserve': reserve, 'reserve_id': reserve_id})


# 新規予約
def reserve_new(request):
    form = ResForm(request.POST or None)
    if form.is_valid():
        res = Res()
        res.name = form.cleaned_data['name']
        res.datetime = form.cleaned_data['datetime']
        res.num = form.cleaned_data['num']
        res.course = form.cleaned_data['course']
        res.comment = form.cleaned_data['comment']

        Res.objects.create(
            name=res.name,
            datetime=res.datetime,
            num=res.num,
            course=res.course,
            comment=res.comment,
        )
        return redirect('reserve:index')

    return render(request, 'reserve/reserve_new.html', {'form': form})


# 予約変更
def edit(request, reserve_id):
    reserve = get_object_or_404(Res, pk=reserve_id)

    if request.method == 'POST':
        form = ResForm(request.POST)
        if form.is_valid():
            res = Res()
            res.name = form.cleaned_data['name']
            res.datetime = form.cleaned_data['datetime']
            res.num = form.cleaned_data['num']
            res.course = form.cleaned_data['course']
            res.comment = form.cleaned_data['comment']

            Res.objects.filter(pk=reserve_id).update(
                name=res.name,
                datetime=res.datetime,
                num=res.num,
                course=res.course,
                comment=res.comment,
            )
            reserve = get_object_or_404(Res, pk=reserve_id)
            return render(request, 'reserve/detail.html', {'reserve': reserve, 'reserve_id': reserve_id})

    else:
        data = {
            'name': reserve.name,
            'datetime': reserve.datetime.strftime('%Y-%m-%dT%H:%M'),  # 日時と時刻の間にTを入れる
            'num': reserve.num,
            'course': reserve.course,
            'comment': reserve.comment,
            }
        form = ResForm(data)

    return render(request, 'reserve/edit.html', {'form': form, 'reserve_id': reserve_id})


# 予約取消
def delete(request, reserve_id):
    reserve = get_object_or_404(Res, id=reserve_id)
    if request.method == 'POST':
        reserve.delete()
        return redirect('reserve:index')
    return render(request, 'reserve/delete.html', {'reserve': reserve})

templates/reserve/delete.html
{% extends "base.html" %}

{% block content %}

{% load static %}

<div>
  <a href="{% url 'reserve:index' %}">予約ホームに戻る</a>
</div>
<table>
    <tr><th>名前</th><td>{{ reserve.name }}</td></tr>
    <tr><th>日時</th><td>{{ reserve.datetime }}</td></tr>
    <tr><th>人数</th><td>{{ reserve.num }}</td></tr>
    <tr><th>コース</th><td>{{ reserve.course }}</td></tr>
    <tr><th>コメント</th><td>{{ reserve.comment }}</td></tr>
</table>
<p>削除してよろしいですか？</p>
<form method="POST" action="">
{% csrf_token %}
<button type="submit" class="btn btn-danger">削除</button>
</form>

{% endblock %}

templates/reserve/detail.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

<!--※予約詳細は管理者&ユーザー自身のみ見れるようにしたい-->

<div class="container">
  <h2 class="mb-3">予約詳細</h2>
  <table class="table">
    <tbody>
      <tr>
        <th>名前</th>
        <td>{{ reserve.name }}</td>
      </tr>
      <tr>
        <th>日時</th>
        <td>{{ reserve.datetime }}</td>
      </tr>
      <tr>
        <th>人数</th>
        <td>{{ reserve.num }}</td>
      </tr>
      <tr>
        <th>コース</th>
        <td>{{ reserve.course }}</td>
      </tr>
      <tr>
        <th>備考</th>
        <td>{{ reserve.comment }}</td>
      </tr>
    </tbody>
  </table>

    <a class="btn btn-primary" href="{% url 'reserve:edit' reserve.id %}" role="button">更新する</a>

    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal01">削除</button>
    <a href="{% url 'reserve:index' %}">予約ホームに戻る</a>

</div>

<div class="modal fade" id="modal01" tabindex="-1" role="dialog" aria-labelledby="modal01-label" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal01-label">削除確認</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"> <span aria-hidden="true">&times;</span> </button>
      </div>
      <div class="modal-body">
        <p>削除してよろしいですか？</p>
        <form method="POST" action="{% url 'reserve:delete' reserve_id %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">削除</button>
        </form>
      </div>
    </div>
  </div>
</div>


{% endblock content %}

templates/reserve/edit.html
{% extends "base.html" %}

{% block content %}

{% load static %}

<div class="container">
  <h2 class="mb-3">予約変更</h2>
  <table class="table">
    <form method="post" action="{% url 'reserve:edit' reserve_id %}">
    {% csrf_token %}
    <tbody>
      <tr>
        <th>名前</th>
        <td>{{ form.name }}</td>
      </tr>
      <tr>
        <th>日時</th>
        <td>{{ form.datetime }}</td>
      </tr>
      <tr>
        <th>人数</th>
        <td>{{ form.num }}</td>
      </tr>
      <tr>
        <th>コース</th>
        <td>{{ form.course }}</td>
      </tr>
      <tr>
        <th>備考</th>
        <td>{{ form.comment }}</td>
      </tr>
    </tbody>
      <tr>
      <td><input class="btn btn-primary" type="submit" value="Submit">
        <input class="btn btn-secondary" type="reset" value="Reset">
      </td>
      <td>
      </td>
      </tr>
    </form>
  </table>

<div>
  <a href="{% url 'reserve:detail' reserve_id %}">予約詳細に戻る</a>
</div>
</div>
{% endblock %}

templates/reserve/index.html
{% extends 'base.html' %}

{% block content %}

<!--※予約一覧は管理者のみ見れるようにしたい-->
<!--ユーザー自身の予約は見れるようにしたい-->

<div class="container">
<h2>予約一覧</h2>

<table class="table">
    <thead>
        <tr>
            <th>名前</th>
            <th>日時</th>
            <th>人数</th>
            <th>コース有無</th>
            <th>備考</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for reserve in reserves %}
        <tr>
            <th><a href="{% url 'reserve:detail' reserve.id %}">{{ reserve.name }}</a></th>
            <td>{{ reserve.datetime }}</td>
            <td>{{ reserve.num }}</td>
            <td>{{ reserve.course }}</td>
            <td>{{ reserve.comment }}</td>
            <td><a class="btn btn-info" href="{% url 'reserve:detail' reserve.id %}" role="button">詳細</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<a class="btn btn-primary" href="{% url 'reserve:new_reserve' %}">新規予約</a>

</div>

{% endblock content %}

templates/reserve/reserve_new.html
{% extends "base.html" %}

{% block content %}

{% load static %}

<div class="container">
  <h2 class="mb-3">新規予約</h2>
  <table class="table">
    <form method="post" action="{% url 'reserve:new_reserve' %}">
    {% csrf_token %}
    <tbody>
      <tr>
        <th>名前</th>
        <td>{{ form.name }}</td>
      </tr>
      <tr>
        <th>日時</th>
        <td>{{ form.datetime }}</td>
      </tr>
      <tr>
        <th>人数</th>
        <td>{{ form.num }}</td>
      </tr>
      <tr>
        <th>コース</th>
        <td>{{ form.course }}</td>
      </tr>
      <tr>
        <th>備考</th>
        <td>{{ form.comment }}</td>
      </tr>
    </tbody>
      <tr>
      <td><input class="btn btn-primary" type="submit" value="Submit">
        <input class="btn btn-secondary" type="reset" value="Reset">
      </td>
      <td>
      </td>
      </tr>

    </form>
  </table>


<div>
  <a href="{% url 'reserve:index' %}">予約ホームに戻る</a>
</div>
</div>

{% endblock %}