cafe_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainpage.urls')),
    path('news/', include('news.urls')),
    path('menu/', include('menu.urls')),
    path('reserve/', include('reserve.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail', views.detail, name='detail'),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('', views.index, name='index'),
    path('post/<int:pk>', views.detail, name='detail'),
]

news/models.py
from django.db import models
from stdimage.models import StdImageField


class Post(models.Model):
    title = models.CharField(max_length=150)
    text = models.TextField(blank=True)
    image = StdImageField(upload_to='picture/news', blank=True, variations={
        'large': (600, 400),
        'thumbnail': (100, 100, True),
        'medium': (300, 200),
    })
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

news/views.py
from django.shortcuts import render
from news.models import Post
from django.shortcuts import get_object_or_404


def index(request):

    keywords = request.GET.get("keyword")

    if keywords:
        keyword_list = keywords.replace('　', ' ').split(' ')

        search_posts = Post.objects.all()

        for keyword in keyword_list:
            search_posts = search_posts.filter(title__contains=keyword)

        search_posts = search_posts.order_by('-created_datetime')
        return render(request, 'news/index.html', {'posts': search_posts, 'keywords': keywords})

    posts = Post.objects.all().order_by('-created_datetime')
    return render(request, 'news/index.html', {'posts': posts})


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'news/detail.html', {"post": post})

templates/news/detail.html
{% extends 'base.html' %}

{% block content %}


<main role="main" class="container">
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
               <h1>{{ post.title }}</h1>
                <p>{{ post.text|linebreaks }}</p>
                {% if post.image %}
                <p><a href="{{ post.image.url }}"><img alt="" src="{{ post.image.large.url }}"/></a></p>
                {% endif %}
            </div>
        </div>
    </div>
</main>

{% endblock content %}

templates/news/index.html
{% extends 'base.html' %}

{% block content %}

<main role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <div class="container">
      <h1 class="display-3">Hello, world!</h1>
      <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
      <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
    </div>
  </div>

    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                {% for post in posts %}
                    <h2>{{ post.title }}</h2>
                    <p>{{ post.text | truncatechars:20  }}</p>
                    {% if  post.image %}
                    <p><img alt="" src="{{ post.image.thumbnail.url }}"/></p>
                    {% endif %}
                    <p><a class="btn btn-secondary" href="{% url 'news:detail' pk=post.pk  %}" role="button">View details &raquo;</a></p>
                {% endfor %}
            </div>
            <div class="col-md-4">
                <div>
                    <h3>記事検索</h3>
                    <form action="#" method="get">
                    <div>
                        <input type="text" id="keyword" name="keyword" placeholder="記事タイトル"
                               value="{{ keywords }}">
                        <button type="submit">検索</button>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock content %}