cafe_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainpage.urls')),
    path('news/', include('news.urls')),
    path('menu/', include('menu.urls')),
    path('reserve/', include('reserve.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainpage/urls.py
from django.urls import path
from . import views

app_name = 'mainpage'
urlpatterns = [
    path('', views.index, name='index'),
]

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail', views.detail, name='detail'),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('', views.index, name='index'),
    path('post/<int:pk>', views.detail, name='detail'),
]

reserve/urls.py
from django.urls import path
from . import views

app_name = 'reserve'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:reserve_id>', views.detail, name='detail'),
    path('new_reserve', views.reserve_new, name='new_reserve'),
    path('<int:reserve_id>/edit', views.edit, name='edit'),
    path('<int:reserve_id>/delete', views.delete, name='delete'),
]

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <script crossorigin="anonymous" integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    {{ form.media }}

    <title>イタリアンカフェ ACミラン</title>
</head>
<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark stick-top">
    <div class="container">
        <!--ブランド-->
        <a class="navbar-brand" href="{% url 'mainpage:index' %}">ACミラン</a>
        <!--切替ボタン-->
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbar-content" aria-controls="navbar-content"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!--ナビゲーション-->
        <div class="collapse navbar-collapse" id="navbar-content">
            <!--左側メニュー-->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'mainpage:index' %}">Top <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'news:index' %}">News</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'menu:index' %}">Menu</a>
                </li>

                <!--ドロップダウン-->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Information
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#shop">Shop</a>
                        <a class="dropdown-item" href="#access">Access</a>
                        <a class="dropdown-item" href="#">Contact</a>
                    </div>
                </li>
            </ul>
            <!--右側メニュー-->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-lnk btn btn-info" href="{% url 'reserve:index' %}">Reservation</a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block content %}
{% endblock %}

<div id="footer">
<footer class="py-4 bg-dark text-light">
  <div class="container text-center">
    <!-- ナビゲーション -->
    <ul class="nav justify-content-center mb-3">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'mainpage:index' %}">Top</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'news:index' %}">News</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'menu:index' %}">Menu</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Information</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'reserve:index' %}">Reserve</a>
      </li>
    </ul>
    <!-- /ナビゲーション -->
    <p><small>Copyright &copy;2018 ACミラン, All Rights Reserved.</small></p>
  </div>
</footer>
</div>

<script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>