cafe_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainpage.urls')),
    path('news/', include('news.urls')),
    path('menu/', include('menu.urls')),
    path('reserve/', include('reserve.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail', views.detail, name='detail'),
]

reserve/urls.py
from django.urls import path
from . import views

app_name = 'reserve'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:reserve_id>', views.detail, name='detail'),
    path('new_reserve', views.reserve_new, name='new_reserve'),
    path('<int:reserve_id>/edit', views.edit, name='edit'),
    path('<int:reserve_id>/delete', views.delete, name='delete'),
]

menu/models.py
from django.db import models
from stdimage.models import StdImageField


class Category(models.Model):
    category_name = models.CharField(max_length=150)
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.category_name


class Menu(models.Model):
    title = models.CharField(max_length=150)
    price = models.IntegerField()
    image = StdImageField(upload_to='picture/menu', blank=True, variations={
        'thumbnail': (300, 225, True),
    })
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Course(models.Model):
    name = models.CharField(max_length=150)
    text = models.TextField(blank=True)
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

menu/views.py
from django.shortcuts import render
from menu.models import Menu
from menu.models import Course


def index(request):
    menus = Menu.objects.all()
    courses = Course.objects.all()
    context = {
                'menus': menus,
                'courses': courses
               }

    return render(request, 'menu/index.html', context)


def detail(request):
    courses = Course.objects.all()
    return render(request, 'menu/detail.html', {'courses': courses})

templates/menu/detail.html
{% extends 'base.html' %}

{% block content %}

    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                {% for course in courses %}

                <h1>{{ course.name }}</h1>
                <p>{{ course.text|linebreaks }}</p>
                <a class="btn btn-primary" href="{% url 'reserve:index' %}" role="button">予約する</a>
                <hr>
                {% endfor %}

            </div>

            <div class="col-md-4">

            </div>
        </div>
    </div>

{% endblock content %}

templates/menu/index.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

<main role="main">
  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Menu List</h1>
      <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
    </div>
  </section>

  <div class="album py-5 bg-light">
      <div class="container">
        <p><h2>Course</h2></p>
        <div class="row">

          {% for course in courses %}
            <div class="col-md-4">
              <div class="card mb-4 shadow-sm">
                <div class="card-body">
                  <p class="card-text">{{ course.name }}</p>
                  <a href="{% url 'menu:detail' %}">コース詳細</a>
                </div>
              </div>
            </div>
          {% endfor %}

        </div>
    </div>
  </div>

  <div class="album py-5 bg-light">
      <div class="container">
        <p><h2>Pizza</h2></p>
        <div class="row">

          {% for menu in menus %}
          {% if  menu.category_id == 1 %}
            <div class="col-md-4">
              <div class="card mb-4 shadow-sm">
                <img class="card-img-top" src="{{ menu.image.thumbnail.url }}" alt="{{menu.title}}">
                <div class="card-body">
                  <p class="card-text">{{ menu.title }}　{{ menu.price }}円</p>
                </div>
              </div>
            </div>
          {% endif%}
          {% endfor %}

        </div>

        <p><h2>Pasta</h2></p>
        <div class="row">
          {% for menu in menus %}
          {% if  menu.category_id == 2 %}
            <div class="col-md-4">
              <div class="card mb-4 shadow-sm">
                <img class="card-img-top" src="{{ menu.image.thumbnail.url }}" alt="{{menu.title}}">
                <div class="card-body">
                  <p class="card-text">{{ menu.title }}　{{ menu.price }}円</p>
                </div>
              </div>
            </div>
          {% endif%}
          {% endfor %}
        </div>

        <p><h2>Salad</h2></p>
        <div class="row">
          {% for menu in menus %}
          {% if  menu.category_id == 3 %}
            <div class="col-md-4">
              <div class="card mb-4 shadow-sm">
                <img class="card-img-top" src="{{ menu.image.thumbnail.url }}" alt="{{menu.title}}">
                <div class="card-body">
                  <p class="card-text">{{ menu.title }}　{{ menu.price }}円</p>
                </div>
              </div>
            </div>
          {% endif%}
          {% endfor %}
        </div>
    </div>
  </div>
</main>



    <div>
        <p>{{menu.title}}</p>
        <p>{{ menu.price }}</p>
        {% if  post.image %}
        <p><img alt="" src="{{ menu.image.thumbnail.url }}"/></p>
        {% endif %}
    </div>


{% endblock content %}